openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/get-resource/{ResourceType}/:
    get:
      tags:
      - api
      operationId: api_device_get_resource
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this Device.
        required: true
        schema:
          type: string
      - name: ResourceType
        in: path
        description: Lab Resource type.
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
                  data:
                    type: string
                required:
                  - result