openapi: 3.0.0
info:
  title: Generated for BFC-TAS
  version: '0.2'
servers:
  - url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: htttp
      scheme: token
security:
  - tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/:
    get:
      tags:
      - api
      operationId: api_devices_device_info
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  data:
                    type: object
                    properties:
                      Hostname:
                        type: string
                      AssignedTo:
                        type: string
                      PowerCommands:
                        type: array
                        items:
                          type: string
                      lab:
                        type: object
                        properties:
                          Zombie:
                            type: object
                            properties:
                              Hostname:
                                type: string
                              IPAddress:
                                type: string
                              URL:
                                type: string
                              DevicePort:
                                type: integer
                          IOCXConnected:
                            type: integer
                          Power:
                            type: object
                            properties:
                              PowerSwitch:
                                type: string
                              PowerSwitchPort:
                                type: integer
                          NetworkBoot:
                            type: object
                            properties:
                              TFTP Boot Directory:
                                type: string
                              NFS Root Directory:
                                type: string
                    required:
                      - Hostname
                      - AssignedTo
                      - PowerCommands
                required:
                  - result
