openapi: 3.0.0
info:
  title: Generated for BFC-TAS
  version: '0.2'
servers:
  - url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
  - tokenAuth: []
paths:
  /api/v0.2/devices/mine/:
    get:
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  data:
                    type: array
                    items:
                      type: string
                required:
                  - result