openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/sdcard/flash/:
    post:
      tags:
      - api
      operationId: api_devices_sdcard_sdcard_image_transfer
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                bmap_file:
                  type: string
                  format: binary
                partition:
                  title: Partition
                  minLength: 1
                  type: string
                flash_tool:
                  type: string
                cmd_args:
                  type: string
                backup:
                  type: boolean
                delete_after:
                  type: boolean
                mkfs:
                  type: boolean
              required:
                - file
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  data:
                    type: object
                    properties:
                      job_id:
                        type: string
                      progress_url:
                        type: string
                  message:
                    type: string
                required:
                  - result
      x-codegen-request-body-name: data