openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/sdcard/partition/:
    post:
      tags:
      - api
      operationId: api_devices_sdcard_sdcard_partition
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                partitions:
                  type: array
                  items: 
                    type: object
                    properties:
                      label:
                        type: string
                      size:
                        type: string
                      type:
                        type: string
                    required:
                      - label
                      - size
                      - type
        required: true
      responses:
        201:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
                required:
                  - result
      x-codegen-request-body-name: data