openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/0.2/devices/{DeviceName}/sdcard/fmanager/*{path}/:
    get:
      tags:
      - api
      operationId: api_devices_sdcard_sdcard_fmanager_list
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: 
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        owner:
                          type: string
                        modified_date:
                          type: string
                        size:
                          type: string
                        symlink_target:
                          type: string
                        file_or_dir_name:
                          type: string
                        'type':
                          type: string