openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/download/ssh/:
    get:
      tags:
      - api
      operationId: api_devices_download_device_download_ssh_formdata
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                device_ip:
                  type: string
                  description: Device IP address
                username:
                  type: string
                  description: SSH username
                path:
                  type: string
                  description: Download File path. Default /
                  default: /
                compress:
                  type: boolean
                  description: compress files on Device before downloading
                  default: false
              required:
                - username
                - device_ip
      responses:
        200:
          description: ""
          content:
            application/vnd.ms-excel:
              schema:
                type: string
                format: binary