openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/import/key/ssh/:
    post:
      tags:
      - api
      operationId: api_devices_import_key_device_import_key_ssh
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                device_ip:
                  type: string
                  description: Device IP address
                username:
                  type: string
                  description: SSH username
                password:
                  type: string
                  description: SSH password
              required:
                - username
                - device_ip
                - password
      responses:
        201:
          description: ""
          content: 
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
                required:
                  - result