openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/0.2/devices/{DeviceName}/portfw/nat/:
    get:
      tags:
      - api
      operationId: api_devices_portfw_nat_read
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  data:
                    type: array
                    items:
                      type: array
                      items: 
                        type: object
                        properties:
                          'type':
                            type: string
                          zport:
                            type: string
                          prot: 
                            type: string
                          dport:
                            type: string
                          dip:
                            type: string
    put:
      tags:
      - api
      operationId: api_devices_portfw_nat_update
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - device_ip
              - dut_port
              - pcol
              - zombie_port
              type: object
              properties:
                device_ip:
                  title: Device ip
                  minLength: 1
                  type: string
                dut_port:
                  title: Dut port
                  minLength: 1
                  type: string
                zombie_port:
                  title: Zombie port
                  minLength: 1
                  type: string
                pcol:
                  title: Pcol
                  minLength: 1
                  type: string
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
      x-codegen-request-body-name: data
    post:
      tags:
      - api
      operationId: api_devices_portfw_nat_create
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - device_ip
              - dut_port
              - pcol
              - zombie_port
              type: object
              properties:
                device_ip:
                  title: Device ip
                  minLength: 1
                  type: string
                dut_port:
                  title: Dut port
                  minLength: 1
                  type: string
                zombie_port:
                  title: Zombie port
                  minLength: 1
                  type: string
                pcol:
                  title: Pcol
                  minLength: 1
                  type: string
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
      x-codegen-request-body-name: data
    delete:
      tags:
      - api
      operationId: api_devices_portfw_nat_delete
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      responses:
        204:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string