openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/0.2/devices/{DeviceName}/hotplug/{hotplug_num}/on/:
    put:
      tags:
      - api
      operationId: api_devices_hotplug_hotplug_on
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: hotplug_num
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                interface:
                  type: string
                device_num: 
                  type: string
                command: 
                  type: string
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  data:
                    type: string
      x-codegen-request-body-name: data