openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/resources/{ResourceName}/camera/capture/:
    get:
      tags:
      - api
      operationId: api_resources_camera_capture
      parameters:
      - name: ResourceName
        in: path
        description: A unique value identifying this camera resource.
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: success/fail
                  data:
                    type: string
                    description: Image URL
                  messsage:
                    type: string
                    description: failure reason
                required:
                  - result