openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/download/serial/:
    get:
      tags:
      - api
      operationId: api_devices_download_device_download_serial
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/vnd.ms-excel:
              schema:
                type: string
                format: binary