openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/upload/serial/:
    post:
      tags:
      - api
      operationId: api_devices_upload_device_upload_serial
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                path:
                  type: string
                  description: Upload File path. Default /
                  default: /
                extract:
                  type: boolean
                  description: extract archive on Device
                  default: false
              required:
                - file
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: 
                    type: string
                  message:
                    type: string
                required:
                  - result
      x-codegen-request-body-name: data