openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/{version}/devices/{hostname}/netboot/fmanager/dir/*{path}/:
    get:
      tags:
      - api
      operationId: api_devices_netboot_fmanager_dir_read
      parameters:
      - name: hostname
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    title: File
                    type: string
                    format: uri
                    readOnly: true
    put:
      tags:
      - api
      operationId: api_devices_netboot_fmanager_dir_update
      parameters:
      - name: hostname
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  title: File
                  type: string
                  format: uri
                  readOnly: true
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    title: File
                    type: string
                    format: uri
                    readOnly: true
      x-codegen-request-body-name: data
    post:
      tags:
      - api
      operationId: api_devices_netboot_fmanager_dir_create
      parameters:
      - name: hostname
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  title: File
                  type: string
                  format: uri
                  readOnly: true
        required: true
      responses:
        201:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    title: File
                    type: string
                    format: uri
                    readOnly: true
      x-codegen-request-body-name: data
    delete:
      tags:
      - api
      operationId: api_devices_netboot_fmanager_dir_delete
      parameters:
      - name: hostname
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
      responses:
        204:
          description: ""
          content: 
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  message:
                    type: string
                  required: 
                    - result



      