openapi: 3.0.1
info:
  title: Generated for EBF-TAS
  version: '0.2'
servers:
- url: https://bfc.timesys.com
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: token
security:
- tokenAuth: []
paths:
  /api/v0.2/devices/{DeviceName}/usb/flash/:
    post:
      tags:
      - api
      operationId: api_devices_usb_usb_image_transfer
      parameters:
      - name: DeviceName
        in: path
        description: A unique value identifying this device.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - partition
              type: object
              properties:
                file:
                  title: File
                  type: string
                  format: uri
                  readOnly: true
                partition:
                  title: Partition
                  minLength: 1
                  type: string
        required: true
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: 
                    type: string
                  data:
                    type: object
                    properties:
                      job_id: 
                        type: string
                      job_url:
                        type: string
      x-codegen-request-body-name: data